##===- lib/Transforms/TypeRecovery/Makefile ----------------*- Makefile -*-===##
#
#              Fracture: The Draper Decompiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

# Path to top level of LLVM hierarchy
LEVEL = ../../..

# Name of the library to build
LIBRARYNAME = TypeRecovery

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
# LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
