##===- dish/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=edit

#
# List libraries that we'll need
#
USEDLIBS = Commands.a Edit.a

# 
# LLVM Components we wish to link with.
#
LINK_COMPONENTS = all-targets ExecutionEngine IRReader JIT Interpreter Linker


#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

